# Generated by Django 4.2.4 on 2023-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='component_category_key',
            new_name='component_category',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='drone_key',
            new_name='drone',
        ),
    ]
