# Generated by Django 4.2.4 on 2023-10-03 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drone', '0002_alter_comment_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='likes',
            field=models.ManyToManyField(related_name='drone_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
